# Generated by Django 4.2.11 on 2024-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformData',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField()),
                ('platform_username', models.CharField()),
                ('verification_status', models.CharField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
    ]
